[Config]
mode=voltage
data_dir=/home/ark/.config/batteryplus
V_FULL_CHG = 4050  // 100% voltage while charging (mV)
V_FULL_DIS = 4000  // 100% voltage while discharging
V_EMPTY_CHG = 3400 // 0% voltage while charging
V_EMPTY_DIS = 3250 // 0% voltage while discharging
INTERNAL_INTERVAL_S = 15  // Internal computation interval
WRITE_INTERVAL_S = 120    // File write interval