# MYMINI key values
# UP          BTN_DPAD_UP
# DOWN        BTN_DPAD_DOWN
# LEFT        BTN_DPAD_LEFT
# RIGHT       BTN_DPAD_RIGHT
# B           BTN_SOUTH
# A           BTN_EAST
# X           BTN_NORTH
# Y           BTN_WEST
# L           BTN_TL
# L2          BTN_TL2
# R           BTN_TR
# R2          BTN_TR2
# L3          BTN_THUMBL
# SELECT      BTN_TRIGGER_HAPPY1
# SATRT       BTN_TRIGGER_HAPPY2
# VOLUMEUP    KEY_VOLUMEUP
# VOLUMEDOWN  KEY_VOLUMEDOWN

# K36S|R36T
# FN          BTN_MODE

# Hotkey: it used to be hardcoded as BTN_TRIGGER_HAPPY5
HOTKEY=BTN_TRIGGER_HAPPY5
# Brightness control
BRIGHT_UP=BTN_DPAD_UP
BRIGHT_DOWN=BTN_DPAD_DOWN
# Volume control
VOL_UP=BTN_DPAD_RIGHT
VOL_DOWN=BTN_DPAD_LEFT
# System volume keys (press directly, no hotkey needed)
VOLUME_UP=KEY_VOLUMEUP
VOLUME_DOWN=KEY_VOLUMEDOWN
